main script: fix `'dict_values' object does not support indexing` error in python3
Fixes: #1

When the else code path is reached in `getPortSuggestion()` the in
python3 the following error can occur:

```
File "/usr/bin/firewall-rpc-helper.py", line 643, in getPortSuggestion
proto = current.values()[0]
TypeError: 'dict_values' object does not support indexing
```

Fix this by explicitly casting to list().